package com.maddox.il2.objects.air;

import com.maddox.il2.fm.FlightModel;
import com.maddox.il2.fm.Mass;
import com.maddox.rts.Finger;
import com.maddox.rts.Property;
import com.maddox.util.HashMapInt;
import java.util.ArrayList;

public class NW_FW_190G1 extends FW_190A4142ATA
{
  public void onAircraftLoaded()
  {
    super.onAircraftLoaded(); this.FM.M.massEmpty -= 81.0F;
  }

  static
  {
    Class localClass = NW_FW_190G1.class; new NetAircraft.SPAWN(localClass); Property.set(localClass, "iconFar_shortClassName", "FW190"); Property.set(localClass, "meshName", "3DO/Plane/Fw-190A-4(Beta)/hier.him"); Property.set(localClass, "PaintScheme", new PaintSchemeFMPar01()); Property.set(localClass, "yearService", 1942.6F); Property.set(localClass, "yearExpired", 1948.0F); Property.set(localClass, "FlightModel", "FlightModels/fw-190a-4_1.42.fmd"); Property.set(localClass, "cockpitClass", new Class[] { CockpitFW_190A4.class }); Property.set(localClass, "LOSElevation", 0.764106F); Aircraft.weaponTriggersRegister(localClass, new int[] { 0, 0, 0, 0, 1, 1, 9, 9, 9, 9, 9, 9, 2, 2, 9, 9, 3 }); Aircraft.weaponHooksRegister(localClass, new String[] { "_MGUN01", "_MGUN02", "_CANNON01", "_CANNON02", "_CANNON03", "_CANNON04", "_ExternalDev03", "_ExternalDev04", "_ExternalDev05", "_ExternalDev06", "_ExternalDev07", "_ExternalDev08", "_ExternalRock01", "_ExternalRock02", "_ExternalDev01", "_ExternalDev02", "_ExternalBomb01" });
    try { ArrayList localArrayList = new ArrayList(); Property.set(localClass, "weaponsList", localArrayList); HashMapInt localHashMapInt = new HashMapInt(); Property.set(localClass, "weaponsMap", localHashMapInt); int i = 17; String str = "default"; Aircraft._WeaponSlot[] arrayOf_WeaponSlot = new Aircraft._WeaponSlot[i]; arrayOf_WeaponSlot[0] = null; arrayOf_WeaponSlot[1] = null; arrayOf_WeaponSlot[2] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[3] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[4] = null; arrayOf_WeaponSlot[5] = null; arrayOf_WeaponSlot[6] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[7] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); for (int j = 8; j < i; j++) arrayOf_WeaponSlot[j] = null; arrayOf_WeaponSlot[14] = new Aircraft._WeaponSlot(9, "PylonETC501FW190", 1); localArrayList.add(str); localHashMapInt.put(Finger.Int(str), arrayOf_WeaponSlot); str = "u81sc250"; arrayOf_WeaponSlot = new Aircraft._WeaponSlot[i]; arrayOf_WeaponSlot[0] = null; arrayOf_WeaponSlot[1] = null; arrayOf_WeaponSlot[2] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[3] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[4] = null; arrayOf_WeaponSlot[5] = null; arrayOf_WeaponSlot[6] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[7] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[8] = null; arrayOf_WeaponSlot[9] = null; arrayOf_WeaponSlot[10] = null; arrayOf_WeaponSlot[11] = null; arrayOf_WeaponSlot[12] = null; arrayOf_WeaponSlot[13] = null; arrayOf_WeaponSlot[14] = new Aircraft._WeaponSlot(9, "PylonETC501FW190", 1); arrayOf_WeaponSlot[15] = null; arrayOf_WeaponSlot[16] = new Aircraft._WeaponSlot(3, "BombGunSC250", 1); localArrayList.add(str); localHashMapInt.put(Finger.Int(str), arrayOf_WeaponSlot); str = "u81sc500"; arrayOf_WeaponSlot = new Aircraft._WeaponSlot[i]; arrayOf_WeaponSlot[0] = null; arrayOf_WeaponSlot[1] = null; arrayOf_WeaponSlot[2] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[3] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[4] = null; arrayOf_WeaponSlot[5] = null; arrayOf_WeaponSlot[6] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[7] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[8] = null; arrayOf_WeaponSlot[9] = null; arrayOf_WeaponSlot[10] = null;

      arrayOf_WeaponSlot[11] = null; arrayOf_WeaponSlot[12] = null; arrayOf_WeaponSlot[13] = null; arrayOf_WeaponSlot[14] = new Aircraft._WeaponSlot(9, "PylonETC501FW190", 1); arrayOf_WeaponSlot[15] = null; arrayOf_WeaponSlot[16] = new Aircraft._WeaponSlot(3, "BombGunSC500", 1); localArrayList.add(str); localHashMapInt.put(Finger.Int(str), arrayOf_WeaponSlot); str = "u82tank"; arrayOf_WeaponSlot = new Aircraft._WeaponSlot[i]; arrayOf_WeaponSlot[0] = null; arrayOf_WeaponSlot[1] = null; arrayOf_WeaponSlot[2] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[3] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[4] = null; arrayOf_WeaponSlot[5] = null; arrayOf_WeaponSlot[6] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[7] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Type_D", 1); arrayOf_WeaponSlot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Type_D", 1); arrayOf_WeaponSlot[10] = null; arrayOf_WeaponSlot[11] = null; arrayOf_WeaponSlot[12] = null; arrayOf_WeaponSlot[13] = null; arrayOf_WeaponSlot[14] = new Aircraft._WeaponSlot(9, "PylonETC501FW190", 1); arrayOf_WeaponSlot[15] = null; arrayOf_WeaponSlot[16] = null; localArrayList.add(str); localHashMapInt.put(Finger.Int(str), arrayOf_WeaponSlot);

      str = "u81sc2502tank"; arrayOf_WeaponSlot = new Aircraft._WeaponSlot[i]; arrayOf_WeaponSlot[0] = null; arrayOf_WeaponSlot[1] = null; arrayOf_WeaponSlot[2] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[3] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[4] = null; arrayOf_WeaponSlot[5] = null; arrayOf_WeaponSlot[6] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[7] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Type_D", 1); arrayOf_WeaponSlot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Type_D", 1); arrayOf_WeaponSlot[10] = null; arrayOf_WeaponSlot[11] = null; arrayOf_WeaponSlot[12] = null; arrayOf_WeaponSlot[13] = null; arrayOf_WeaponSlot[14] = new Aircraft._WeaponSlot(9, "PylonETC501FW190", 1); arrayOf_WeaponSlot[15] = null; arrayOf_WeaponSlot[16] = new Aircraft._WeaponSlot(3, "BombGunSC250", 1); localArrayList.add(str); localHashMapInt.put(Finger.Int(str), arrayOf_WeaponSlot); str = "u81sc5002tank"; arrayOf_WeaponSlot = new Aircraft._WeaponSlot[i]; arrayOf_WeaponSlot[0] = null; arrayOf_WeaponSlot[1] = null; arrayOf_WeaponSlot[2] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200); arrayOf_WeaponSlot[3] = new Aircraft._WeaponSlot(1, "MGunMG15120MGs", 200);

      arrayOf_WeaponSlot[4] = null; arrayOf_WeaponSlot[5] = null; arrayOf_WeaponSlot[6] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[7] = new Aircraft._WeaponSlot(9, "PylonETC250", 1); arrayOf_WeaponSlot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Type_D", 1); arrayOf_WeaponSlot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Type_D", 1); arrayOf_WeaponSlot[10] = null; arrayOf_WeaponSlot[11] = null; arrayOf_WeaponSlot[12] = null; arrayOf_WeaponSlot[13] = null; arrayOf_WeaponSlot[14] = new Aircraft._WeaponSlot(9, "PylonETC501FW190", 1); arrayOf_WeaponSlot[15] = null; arrayOf_WeaponSlot[16] = new Aircraft._WeaponSlot(3, "BombGunSC500", 1); localArrayList.add(str); localHashMapInt.put(Finger.Int(str), arrayOf_WeaponSlot); str = "none"; arrayOf_WeaponSlot = new Aircraft._WeaponSlot[i]; for (int k = 0; k < i; k++) arrayOf_WeaponSlot[k] = null; localArrayList.add(str); localHashMapInt.put(Finger.Int(str), arrayOf_WeaponSlot);
    }
    catch (Exception localException)
    {
    }
  }
}